---   # rust-bitcoincore-rpc CI: If you edit this file please update README.md
on:   # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - 'test-ci/**'
  pull_request:

name: Continuous integration

jobs:
  Integration:                  # 1 job for each Bitcoin Core version.
    name: Integration tests - stable toolchain
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Select toolchain"
        uses: dtolnay/rust-toolchain@stable
      - name: "Run integration tests"
        run: ./contrib/integration_test.sh
